### ISSUE TITLE
Error in RStudio: Registered S3 methods overwritten by 'rgl'

### ISSUE THREAD

**Issue by ZP254** [mlampros/fitbitViz#3]
Hi, thank you very much for sharing **FitbitViz**. I successfully installed your package in my RStudio, however, it turned out some errors. Could you help me to have a look at my issue? Thanks a lot. 

`Registered S3 methods overwritten by 'rgl':
  method               from
  knit_print.rglId         
  knit_print.rglOpen3d     
  sew.rglRecordedplot      
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error: package or namespace load failed for ‘fitbitViz’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: rgl.init(initValue, onlyNULL)
  error: OpenGL is not available in this build
In addition: Warning messages:
1: 	Loading rgl's DLL failed. 
	This build of rgl depends on XQuartz, which failed to load.
 See the discussion in https://stackoverflow.com/a/66127391/2554330 
2: Trying without OpenGL... `

**Comment by mlampros** [comment]
hi @Kyle090471,

I assume you use Mac OSx because the [stackoverflow (SO) issue that you mention](https://stackoverflow.com/a/66127391/8302386) is for this Operating System. 
The SO issue tells that it is related with the 'Xquartz'  version that is required for the 'rgl' package. In the[ Suggests of my DESCRIPTION file](https://github.com/mlampros/fitbitViz/blob/master/DESCRIPTION#L49) I call the 'rgl' package which is required to run the vignette so I assume you want to reproduce the functions in the vignette.
In my opinion if you want to resolve this issue you have to make sure that  'Xquartz' works for 'rgl' on your Mac OSx and then move on and try to reproduce the vignette. You can also go through the[ issues of the 'rgl' package ](https://github.com/dmurdoch/rgl/issues) and especially the ones related to Mac OSx such as[ this one](https://github.com/dmurdoch/rgl/issues/45)
Once you have a working rgl you can come back to reproduce the vignette functions of the 'fitbitViz' package

**Comment by ZP254** [comment]
Thank you very much @mlampros for your speedy reply! My issue seems to be solved after I installed the Xquartz software (My Macbook did not have it before your suggenstion). Now, there is no error showing up following the 'library(FitbitViz)' command in RStudio. 

Could you do me another small favour? 

I simply wish to visualise a 3D cardiac map with the terrains (elevated buildings, steps, roof gardens) using your LeafGL Map code (see below). I have downloaded my TCX file [43050066481.tcx.zip](https://github.com/mlampros/fitbitViz/files/7788999/43050066481.tcx.zip) through my Fitbit account. I have replaced the file path in this code from your website [https://mlampros.github.io/2021/05/20/fitbitViz_package/](url)

`res_lft = fitbitViz::leafGL_point_coords(dat_gps_tcx = '/Users/myusername/............/43050066481.tcx',
                                         color_points_column = 'AltitudeMeters',
                                         provider = leaflet::providers$Esri.WorldImagery,
                                         option_viewer = rstudioapi::viewer,
                                         CRS = 4326)                             
res_lft`

However, it shows an error: `Error in UseMethod("st_as_sf") : 
  no applicable method for 'st_as_sf' applied to an object of class "character"`

Could you give me any advice on that? I assume the data frame of my TCX file might not fit the leafGL command. I hope it won't be a challenging thing for you.  

Thanks again!

**Comment by mlampros** [comment]
the 'dat_gps_tcx' parameter of the 'fitbitViz::leafGL_point_coords()' function is actually a data.table (you can see that in the documentation of the package) but you give as input a .txt file. I assume you don't have a fitbit device but you want to visualize the data of another device, that's ok but you have to modify you input data. The format of the 'res_tcx' variable in the [blog post](http://mlampros.github.io/2021/05/20/fitbitViz_package/) is the following:

```R

> res_tcx = fitbitViz::GPS_TCX_data(log_id = log_id,
                                   user_id = USER_ID,
                                   token = token,
                                   time_zone = 'Europe/Athens',
                                   verbose = VERBOSE)
> str(res_tcx)
Classes ‘data.table’ and 'data.frame':	5840 obs. of  7 variables:
 $ latitude      : num  38 38 38 38 38 ...
 $ longitude     : num  23.8 23.8 23.8 23.8 23.8 ...
 $ AltitudeMeters: num  218 218 218 218 218 ...
 $ DistanceMeters: num  0 0 0 0 0 0 0 0 0 0 ...
 $ HeartRate_Bpm : num  99 99 99 99 99 99 99 99 99 100 ...
 $ Date          : Date, format: "2021-03-13" "2021-03-13" "2021-03-13" "2021-03-13" ...
 $ Time          : 'hms' num  16:02:06 16:02:11 16:02:12 16:02:13 ...
  ..- attr(*, "units")= chr "secs"
 - attr(*, ".internal.selfref")=<externalptr> 
> head(res_tcx)
   latitude longitude AltitudeMeters DistanceMeters HeartRate_Bpm       Date     Time
1: 37.96921  23.77290          218.1              0            99 2021-03-13 16:02:06
2: 37.96921  23.77290          218.1              0            99 2021-03-13 16:02:11
3: 37.96921  23.77290          218.1              0            99 2021-03-13 16:02:12
4: 37.96921  23.77290          218.1              0            99 2021-03-13 16:02:13
5: 37.96921  23.77290          218.0              0            99 2021-03-13 16:02:14
6: 37.96921  23.77291          218.0              0            99 2021-03-13 16:02:15
```
now, if you read your .tcx file using the 'XML' package you will observe that it looks like,

```R
pth_tcx = '43050066481.tcx'
dat_tcx = readLines(con = pth_tcx, warn = FALSE)

tcx_dat = XML::xmlParse(dat_tcx)
tcx_lst = XML::xmlToList(tcx_dat)
str(tcx_lst)

# > str(tcx_lst)
# List of 1
# $ Activities:List of 1
# ..$ Activity:List of 4
# .. ..$ Id     : chr "2021-09-24T13:20:33.000+02:00"
# .. ..$ Lap    :List of 7
# .. .. ..$ TotalTimeSeconds: chr "2315.0"
# .. .. ..$ DistanceMeters  : chr "3174.38"
# .. .. ..$ Calories        : chr "358"
# .. .. ..$ Intensity       : chr "Active"
# .. .. ..$ TriggerMethod   : chr "Manual"
# .. .. ..$ Track           :List of 1808
# .. .. .. ..$ Trackpoint:List of 5
# .. .. .. .. ..$ Time          : chr "2021-09-24T13:20:33.000+02:00"
# .. .. .. .. ..$ Position      :List of 2
# .. .. .. .. .. ..$ LatitudeDegrees : chr "41.893776059150696"
# .. .. .. .. .. ..$ LongitudeDegrees: chr "12.492316603660583"
# .. .. .. .. ..$ AltitudeMeters: chr "39.25240000602284"
# .. .. .. .. ..$ DistanceMeters: chr "0.0"
# .. .. .. .. ..$ HeartRateBpm  :List of 1
# .. .. .. .. .. ..$ Value: chr "107"
```
you have to modify this nested list (also the data types of the columns) to match the format of the 'res_tcx' so that you don't receive the error when you use the 'fitbitViz::leafGL_point_coords()' function

**Comment by ZP254** [comment]
Thank you @mlampros for your advice. I spent a long time modifying the data structure and it worked. My raw data was downloaded from Fitbit's website and monitored via Fitbit Charge 4 during a single running exercise. To make things easier for other people, I've written down the code for converting raw TCX below for using the 'fitbitViz::leafGL_point_coords()' function.

```
#View your Fitbit's raw data structure. change the file path.

pth_tcx = "/Users/YourUserName/......./raw_tcx_data_file.tcx"
dat_tcx = readLines(con = pth_tcx, warn = FALSE)

tcx_dat = XML::xmlParse(dat_tcx)
tcx_lst = XML::xmlToList(tcx_dat)
str(tcx_lst)

#Extract six nodes from the raw data: geocoordinates (2 columns), altitude, distance, cardiac, date, time,

gco <- xmlToDataFrame(nodes <- getNodeSet(tcx_dat, "//ns:Position", "ns"))
colnames(gco) <- c('latitude','longitude')
alt <- xmlToDataFrame(nodes <- getNodeSet(tcx_dat, "//ns:AltitudeMeters", "ns"))
colnames(alt) <- c('AltitudeMeters')
dis <- xmlToDataFrame(nodes <- getNodeSet(tcx_dat, "//ns:DistanceMeters", "ns"))
dis <- data.frame(dis[-c(1),])
colnames(dis) <- c('DistanceMeters')
hr <- xmlToDataFrame(nodes <- getNodeSet(tcx_dat, "//ns:HeartRateBpm", "ns"))
colnames(hr) <- c('HeartRate_Bpm')
dt <- xmlToDataFrame(nodes <- getNodeSet(tcx_dat, "//ns:Time", "ns"))
date <- data.frame(as.Date(substr(dt$text, 1, 10)))
colnames(date) <- c('Date')
time <- data.frame(as.POSIXct(strptime(substr(dt$text, 12, 19), '%H:%M:%S')))
colnames(time) <- c('Time')

#Combine 6 nodes into a data frame and ensure all of them are numeric, except the date and time. 

res_tcx <- cbind(gco, alt, dis, hr, date, time)
res_tcx$latitude <- as.numeric(res_tcx$latitude)
res_tcx$longitude <- as.numeric(res_tcx$longitude)
res_tcx$AltitudeMeters <- as.numeric(res_tcx$AltitudeMeters)
res_tcx$DistanceMeters <- as.numeric(res_tcx$DistanceMeters)
res_tcx$HeartRate_Bpm <- as.numeric(res_tcx$HeartRate_Bpm)

# using FitbitViz tool to draw the cardiac map.  

res_lft = fitbitViz::leafGL_point_coords(dat_gps_tcx = res_tcx, color_points_column = 'AltitudeMeters', provider = leaflet::providers$Esri.WorldImagery, option_viewer = rstudioapi::viewer, CRS = 4326) 
res_lft

```
<img width="1440" alt="RStudio_img" src="https://user-images.githubusercontent.com/45998038/147688425-62bdb531-8a6d-4f12-83cd-46b4b898766a.png">

**Comment by mlampros** [comment]
good to hear that it worked
